export const gameData = [
  {
    id: 1,
    name: "Metal Gear Solid",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 1998,
    rating: 9.1,
    difficulty: 7,
    popularity: 86,
    country: "Japan",
    sales: 6,
    developer: "Konami",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 2,
    name: "Grand Theft Auto V",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2013,
    rating: 9.0,
    difficulty: 4,
    popularity: 98,
    country: "USA",
    sales: 185,
    developer: "Rockstar",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 3,
    name: "Among Us",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 2018,
    rating: 7.9,
    difficulty: 2,
    popularity: 88,
    country: "USA",
    sales: 4,
    developer: "InnerSloth",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 4,
    name: "The Last of Us",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2013,
    rating: 9.6,
    difficulty: 6,
    popularity: 93,
    country: "USA",
    sales: 20,
    developer: "Naughty Dog",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 5,
    name: "Super Smash Bros. Ultimate",
    genre: "Lucha",
    platform: "Nintendo",
    releaseYear: 2018,
    rating: 9.2,
    difficulty: 6,
    popularity: 91,
    country: "Japan",
    sales: 28,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 6,
    name: "Red Dead Redemption 2",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2018,
    rating: 9.7,
    difficulty: 5,
    popularity: 94,
    country: "USA",
    sales: 50,
    developer: "Rockstar",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 7,
    name: "PUBG",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2017,
    rating: 7.8,
    difficulty: 7,
    popularity: 89,
    country: "Korea",
    sales: 75,
    developer: "PUBG Corp",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 8,
    name: "Guitar Hero",
    genre: "Puzzle",
    platform: "PlayStation",
    releaseYear: 2005,
    rating: 8.4,
    difficulty: 4,
    popularity: 75,
    country: "USA",
    sales: 6,
    developer: "Harmonix",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 9,
    name: "Stardew Valley",
    genre: "Simulación",
    platform: "PC",
    releaseYear: 2016,
    rating: 8.9,
    difficulty: 2,
    popularity: 82,
    country: "USA",
    sales: 20,
    developer: "ConcernedApe",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 10,
    name: "Hades",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2020,
    rating: 9.0,
    difficulty: 8,
    popularity: 83,
    country: "USA",
    sales: 5,
    developer: "Supergiant",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 11,
    name: "Rocket League",
    genre: "Deportes",
    platform: "PC",
    releaseYear: 2015,
    rating: 8.7,
    difficulty: 6,
    popularity: 87,
    country: "USA",
    sales: 1,
    developer: "Psyonix",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 12,
    name: "Hollow Knight",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2017,
    rating: 9.0,
    difficulty: 8,
    popularity: 85,
    country: "Australia",
    sales: 3,
    developer: "Team Cherry",
    isMainstream: false,
    region: "Oceania",
  },
  {
    id: 13,
    name: "Minecraft",
    genre: "Simulación",
    platform: "PC",
    releaseYear: 2011,
    rating: 9.5,
    difficulty: 3,
    popularity: 100,
    country: "Sweden",
    sales: 300,
    developer: "Mojang",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 14,
    name: "Dark Souls III",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2016,
    rating: 9.3,
    difficulty: 10,
    popularity: 89,
    country: "Japan",
    sales: 10,
    developer: "FromSoftware",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 15,
    name: "Celeste",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2018,
    rating: 8.8,
    difficulty: 9,
    popularity: 80,
    country: "Canada",
    sales: 2,
    developer: "Maddy Makes Games",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 16,
    name: "The Witcher 3",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2015,
    rating: 9.8,
    difficulty: 6,
    popularity: 96,
    country: "Poland",
    sales: 40,
    developer: "CD Projekt",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 17,
    name: "Cyberpunk 2077",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2020,
    rating: 7.2,
    difficulty: 5,
    popularity: 85,
    country: "Poland",
    sales: 20,
    developer: "CD Projekt",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 18,
    name: "Animal Crossing",
    genre: "Simulación",
    platform: "Nintendo",
    releaseYear: 2020,
    rating: 9.0,
    difficulty: 1,
    popularity: 90,
    country: "Japan",
    sales: 42,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 19,
    name: "Fortnite",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2017,
    rating: 8.0,
    difficulty: 6,
    popularity: 95,
    country: "USA",
    sales: 0,
    developer: "Epic Games",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 20,
    name: "Ori and the Will of the Wisps",
    genre: "Aventura",
    platform: "Xbox",
    releaseYear: 2020,
    rating: 9.0,
    difficulty: 7,
    popularity: 78,
    country: "USA",
    sales: 2,
    developer: "Moon Studios",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 21,
    name: "Call of Duty: Modern Warfare",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2019,
    rating: 8.5,
    difficulty: 5,
    popularity: 92,
    country: "USA",
    sales: 30,
    developer: "Infinity Ward",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 22,
    name: "Pac-Man",
    genre: "Puzzle",
    platform: "Arcade",
    releaseYear: 1980,
    rating: 8.5,
    difficulty: 6,
    popularity: 95,
    country: "Japan",
    sales: 15,
    developer: "Namco",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 23,
    name: "Tetris",
    genre: "Puzzle",
    platform: "Retro",
    releaseYear: 1984,
    rating: 9.0,
    difficulty: 5,
    popularity: 98,
    country: "Russia",
    sales: 520,
    developer: "Pajitnov",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 24,
    name: "Street Fighter II",
    genre: "Lucha",
    platform: "Arcade",
    releaseYear: 1991,
    rating: 9.2,
    difficulty: 8,
    popularity: 90,
    country: "Japan",
    sales: 15,
    developer: "Capcom",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 25,
    name: "Chrono Trigger",
    genre: "RPG",
    platform: "Retro",
    releaseYear: 1995,
    rating: 9.8,
    difficulty: 6,
    popularity: 85,
    country: "Japan",
    sales: 3,
    developer: "Square",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 26,
    name: "FIFA 23",
    genre: "Deportes",
    platform: "PlayStation",
    releaseYear: 2022,
    rating: 7.5,
    difficulty: 4,
    popularity: 88,
    country: "Canada",
    sales: 31,
    developer: "EA Sports",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 27,
    name: "Valorant",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2020,
    rating: 8.3,
    difficulty: 8,
    popularity: 89,
    country: "USA",
    sales: 0,
    developer: "Riot Games",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 28,
    name: "Fall Guys",
    genre: "Puzzle",
    platform: "PC",
    releaseYear: 2020,
    rating: 7.8,
    difficulty: 3,
    popularity: 82,
    country: "UK",
    sales: 2,
    developer: "Mediatonic",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 29,
    name: "Apex Legends",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2019,
    rating: 8.7,
    difficulty: 7,
    popularity: 91,
    country: "USA",
    sales: 0,
    developer: "Respawn",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 30,
    name: "God of War",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2018,
    rating: 9.5,
    difficulty: 6,
    popularity: 92,
    country: "USA",
    sales: 23,
    developer: "Santa Monica",
    isMainstream: true,
    region: "North America",
  },
]

// Extended industry data for broader narrative
export const industryData = {
  globalMarketSize: [
    { year: 1980, value: 0.2, region: "Global" },
    { year: 1985, value: 3.2, region: "Global" },
    { year: 1990, value: 5.1, region: "Global" },
    { year: 1995, value: 7.4, region: "Global" },
    { year: 2000, value: 23.2, region: "Global" },
    { year: 2005, value: 31.6, region: "Global" },
    { year: 2010, value: 67.3, region: "Global" },
    { year: 2015, value: 91.8, region: "Global" },
    { year: 2020, value: 159.3, region: "Global" },
    { year: 2023, value: 184.0, region: "Global" },
  ],

  regionalMarkets: [
    { region: "Asia-Pacific", marketShare: 49, revenue: 90.1, growth: 6.2 },
    { region: "North America", marketShare: 24, revenue: 44.2, growth: 2.4 },
    { region: "Europe", marketShare: 23, revenue: 42.3, growth: 3.1 },
    { region: "Latin America", marketShare: 3, revenue: 5.5, growth: 8.7 },
    { region: "Middle East & Africa", marketShare: 1, revenue: 1.9, growth: 12.3 },
  ],

  platformEvolution: [
    { decade: "1970s", dominant: "Arcade", description: "Nacimiento de los videojuegos comerciales" },
    { decade: "1980s", dominant: "Consolas Domésticas", description: "Era dorada de Nintendo y Atari" },
    { decade: "1990s", dominant: "PC + Consolas", description: "Revolución 3D y CD-ROM" },
    { decade: "2000s", dominant: "Consolas HD", description: "PlayStation, Xbox y gráficos realistas" },
    { decade: "2010s", dominant: "Mobile + Digital", description: "Smartphones y distribución digital" },
    { decade: "2020s", dominant: "Cloud + VR/AR", description: "Streaming y realidad extendida" },
  ],

  genreEvolution: [
    { genre: "Arcade", peak: "1980s", currentStatus: "Retro/Indie", impact: "Fundacional" },
    { genre: "Plataformas", peak: "1990s", currentStatus: "Indie/Nostalgia", impact: "Icónico" },
    { genre: "RPG", peak: "2000s", currentStatus: "Mainstream", impact: "Narrativo" },
    { genre: "FPS", peak: "2010s", currentStatus: "Esports", impact: "Competitivo" },
    { genre: "Battle Royale", peak: "2020s", currentStatus: "Dominante", impact: "Social" },
    { genre: "Simulación", peak: "Continuo", currentStatus: "Creciente", impact: "Educativo" },
  ],

  demographicShifts: [
    { year: 2000, avgAge: 28, femalePercent: 38, casualPercent: 25 },
    { year: 2005, avgAge: 30, femalePercent: 40, casualPercent: 35 },
    { year: 2010, avgAge: 32, femalePercent: 42, casualPercent: 45 },
    { year: 2015, avgAge: 34, femalePercent: 44, casualPercent: 55 },
    { year: 2020, avgAge: 35, femalePercent: 46, casualPercent: 65 },
    { year: 2023, avgAge: 36, femalePercent: 48, casualPercent: 70 },
  ],

  technologyMilestones: [
    { year: 1972, milestone: "Pong", impact: "Primer videojuego comercial exitoso" },
    { year: 1985, milestone: "Super Mario Bros", impact: "Definió el género de plataformas" },
    { year: 1993, milestone: "Doom", impact: "Popularizó los FPS y el multijugador" },
    { year: 1996, milestone: "Pokémon", impact: "Gaming portátil y fenómeno cultural" },
    { year: 2004, milestone: "World of Warcraft", impact: "MMORPGs mainstream" },
    { year: 2007, milestone: "iPhone", impact: "Revolución del gaming móvil" },
    { year: 2016, milestone: "Pokémon GO", impact: "Realidad aumentada masiva" },
    { year: 2020, milestone: "Among Us", impact: "Gaming social en pandemia" },
  ],
}

// Helper functions for data analysis
export const getGenreDistribution = () => {
  const genres = {}
  gameData.forEach((game) => {
    genres[game.genre] = (genres[game.genre] || 0) + 1
  })
  return Object.entries(genres).map(([genre, count]) => ({ genre, count }))
}

export const getRegionalDistribution = () => {
  const regions = {}
  gameData.forEach((game) => {
    regions[game.region] = (regions[game.region] || 0) + 1
  })
  return Object.entries(regions).map(([region, count]) => ({ region, count }))
}

export const getDecadeDistribution = () => {
  const decades = {}
  gameData.forEach((game) => {
    const decade = Math.floor(game.releaseYear / 10) * 10
    const decadeLabel = `${decade}s`
    decades[decadeLabel] = (decades[decadeLabel] || 0) + 1
  })
  return Object.entries(decades).map(([decade, count]) => ({ decade, count }))
}

export const getDifficultyVsPopularity = () => {
  return gameData.map((game) => ({
    name: game.name,
    difficulty: game.difficulty,
    popularity: game.popularity,
    rating: game.rating,
    genre: game.genre,
    isMainstream: game.isMainstream,
  }))
}

export const getMainstreamVsNiche = () => {
  const mainstream = gameData.filter((game) => game.isMainstream)
  const niche = gameData.filter((game) => !game.isMainstream)

  return {
    mainstream: {
      count: mainstream.length,
      avgRating: mainstream.reduce((sum, game) => sum + game.rating, 0) / mainstream.length,
      avgPopularity: mainstream.reduce((sum, game) => sum + game.popularity, 0) / mainstream.length,
      avgDifficulty: mainstream.reduce((sum, game) => sum + game.difficulty, 0) / mainstream.length,
    },
    niche: {
      count: niche.length,
      avgRating: niche.reduce((sum, game) => sum + game.rating, 0) / niche.length,
      avgPopularity: niche.reduce((sum, game) => sum + game.popularity, 0) / niche.length,
      avgDifficulty: niche.reduce((sum, game) => sum + game.difficulty, 0) / niche.length,
    },
  }
}

export const getEvolutionByDecade = () => {
  const decades = {}
  gameData.forEach((game) => {
    const decade = Math.floor(game.releaseYear / 10) * 10
    if (!decades[decade]) {
      decades[decade] = {
        decade,
        games: [],
        avgRating: 0,
        avgDifficulty: 0,
        totalSales: 0,
        genreCount: {},
      }
    }
    decades[decade].games.push(game)
    decades[decade].totalSales += game.sales
    decades[decade].genreCount[game.genre] = (decades[decade].genreCount[game.genre] || 0) + 1
  })

  return Object.values(decades).map((decade) => ({
    ...decade,
    avgRating: decade.games.reduce((sum, game) => sum + game.rating, 0) / decade.games.length,
    avgDifficulty: decade.games.reduce((sum, game) => sum + game.difficulty, 0) / decade.games.length,
    gameCount: decade.games.length,
    topGenre: Object.entries(decade.genreCount).sort(([, a], [, b]) => b - a)[0]?.[0] || "N/A",
  }))
}
