export const gameData = [
  { id: 1, name: "Metal Gear Solid", genre: "Carreras", platform: "Xbox", releaseYear: 2017, rating: 9.1, difficulty: 7, popularity: 86 },
  { id: 2, name: "Grand Theft Auto V", genre: "Estrategia", platform: "PC", releaseYear: 2008, rating: 9.0, difficulty: 4, popularity: 98 },
  { id: 3, name: "Among Us", genre: "Simulación", platform: "PC", releaseYear: 1984, rating: 7.9, difficulty: 2, popularity: 88 },
  { id: 4, name: "The Last of Us", genre: "Puzzle", platform: "Retro", releaseYear: 2018, rating: 9.6, difficulty: 9, popularity: 93 },
  { id: 5, name: "Super Smash Bros. Ultimate", genre: "Estrategia", platform: "Xbox", releaseYear: 1994, rating: 9.2, difficulty: 6, popularity: 91 },
  { id: 6, name: "Red Dead Redemption 2", genre: "RPG", platform: "PC", releaseYear: 2008, rating: 9.7, difficulty: 8, popularity: 94 },
  { id: 7, name: "PUBG", genre: "Acción", platform: "Retro", releaseYear: 1985, rating: 7.8, difficulty: 3, popularity: 79 },
  { id: 8, name: "Guitar Hero", genre: "Puzzle", platform: "PC", releaseYear: 2002, rating: 4.4, difficulty: 1, popularity: 50 },
  { id: 9, name: "Stardew Valley", genre: "Deportes", platform: "PC", releaseYear: 1988, rating: 8.9, difficulty: 2, popularity: 82 },
  { id: 10, name: "Hades", genre: "Simulación", platform: "PlayStation", releaseYear: 2020, rating: 9.0, difficulty: 10, popularity: 83 },
  { id: 11, name: "Rocket Brawl", genre: "RPG", platform: "Xbox", releaseYear: 2024, rating: 2.9, difficulty: 5, popularity: 57 },
  { id: 12, name: "Hollow Knight", genre: "RPG", platform: "Retro", releaseYear: 1992, rating: 9.0, difficulty: 8, popularity: 85 },
  { id: 13, name: "Minecraft", genre: "Deportes", platform: "Arcade", releaseYear: 2013, rating: 9.5, difficulty: 3, popularity: 100 },
  { id: 14, name: "Dark Souls III", genre: "Simulación", platform: "Retro", releaseYear: 1998, rating: 9.3, difficulty: 10, popularity: 89 },
  { id: 15, name: "Celeste", genre: "RPG", platform: "Retro", releaseYear: 1980, rating: 8.8, difficulty: 9, popularity: 80 },
  { id: 16, name: "Dreamforge", genre: "Puzzle", platform: "PC", releaseYear: 1993, rating: 8.6, difficulty: 7, popularity: 84 },
  { id: 17, name: "Cyber Drift", genre: "Lucha", platform: "PlayStation", releaseYear: 2023, rating: 3.9, difficulty: 2, popularity: 60 },
  { id: 18, name: "Animal Crossing", genre: "Estrategia", platform: "Arcade", releaseYear: 2005, rating: 9.0, difficulty: 1, popularity: 90 },
  { id: 19, name: "Fortnite", genre: "Lucha", platform: "Retro", releaseYear: 2012, rating: 8.0, difficulty: 6, popularity: 95 },
  { id: 20, name: "Legendborn", genre: "Simulación", platform: "Nintendo", releaseYear: 1983, rating: 8.0, difficulty: 4, popularity: 41 },
  { id: 21, name: "Call of Duty: Modern Warfare", genre: "Deportes", platform: "Xbox", releaseYear: 2019, rating: 8.5, difficulty: 8, popularity: 89 },
  { id: 22, name: "Turbo Trails", genre: "Carreras", platform: "Retro", releaseYear: 1987, rating: 3.4, difficulty: 5, popularity: 35 },
  { id: 23, name: "Void Runners", genre: "Aventura", platform: "Retro", releaseYear: 1991, rating: 4.9, difficulty: 7, popularity: 43 },
  { id: 24, name: "Frostborn Legacy", genre: "Acción", platform: "Arcade", releaseYear: 1996, rating: 5.0, difficulty: 10, popularity: 94 },
  { id: 25, name: "Chrono Shift", genre: "Aventura", platform: "Retro", releaseYear: 1981, rating: 3.3, difficulty: 1, popularity: 0 },
  { id: 26, name: "Echo Realms", genre: "Carreras", platform: "PlayStation", releaseYear: 2020, rating: 8.9, difficulty: 6, popularity: 90 },
  { id: 27, name: "Pixel Siege", genre: "RPG", platform: "PC", releaseYear: 1997, rating: 4.3, difficulty: 3, popularity: 39 },
  { id: 28, name: "Galaxy Clash", genre: "Acción", platform: "Nintendo", releaseYear: 1986, rating: 3.5, difficulty: 2, popularity: 2 },
  { id: 29, name: "Zenith Tactics", genre: "Lucha", platform: "Retro", releaseYear: 2014, rating: 9.0, difficulty: 8, popularity: 75 },
  { id: 30, name: "God of War", genre: "Aventura", platform: "PlayStation", releaseYear: 1991, rating: 9.5, difficulty: 9, popularity: 92 }
];
